<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatmessage.proto

namespace GPBMetadata;

class Chatmessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0afe010a11636861746d6573736167652e70726f746f120b636861746d65737361676522470a0b706f73744d657373616765120f0a07757365725f696418012001280d120f0a076d65737361676518022001280912160a0e7461726765745f757365725f696418032001280d22520a0a6765744d657373616765120a0a02696418012001280d120f0a07757365725f696418022001280d120f0a076d65737361676518032001280912160a0e7461726765745f757365725f696418042001280d22370a0b6c6973744d65737361676512280a076d65737361676518012003280b32172e636861746d6573736167652e6765744d657373616765620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

